version: "3.9"
services:
  identity:
    build:
      context: docker/app
    volumes:
      - ./src:/src
    working_dir: /src/identity
    ports:
      - "127.0.0.1:3002:3000"
    environment:
      IDENTITY_POSTGRES: "host=db port=5432 user=postgres password=postgres dbname=identity sslmode=disable"
      HTTP_PORT: 3000
    depends_on:
      - flyway
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/identity -user=postgres -password=postgres migrate
    volumes:
      - ./sql/identity:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init.sh