version: "3.9"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/identity -user=postgres -password=postgres migrate
    volumes:
      - ./sql/identity:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init.sh